"""corpus tables and cohort baselines

Revision ID: e35e8eca6772
Revises: 0001_initial_schema
Create Date: 2026-09-13 04:08:30.200951
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002_corpus_tables"
down_revision: str | None = "0001_initial_schema"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cohort_baselines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("metric", sa.String(length=80), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column(
            "dimensions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("specificity", sa.Integer(), nullable=False),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.Column("mean", sa.Float(), nullable=True),
        sa.Column("std", sa.Float(), nullable=True),
        sa.Column("p10", sa.Float(), nullable=True),
        sa.Column("p25", sa.Float(), nullable=True),
        sa.Column("p50", sa.Float(), nullable=True),
        sa.Column("p75", sa.Float(), nullable=True),
        sa.Column("p90", sa.Float(), nullable=True),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.Column("cohort_key", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cohort_baselines")),
        sa.UniqueConstraint(
            "metric", "source", "specificity", "cohort_key", name="uq_baseline_cell"
        ),
    )
    op.create_index(
        "ix_baseline_lookup", "cohort_baselines", ["metric", "source", "specificity"], unique=False
    )
    op.create_index(
        op.f("ix_cohort_baselines_metric"), "cohort_baselines", ["metric"], unique=False
    )
    op.create_index(
        op.f("ix_cohort_baselines_source"), "cohort_baselines", ["source"], unique=False
    )
    op.create_table(
        "corpus_matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.String(length=64), nullable=False),
        sa.Column("map_name", sa.String(length=120), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("num_players", sa.Integer(), nullable=False),
        sa.Column("leaderboard", sa.String(length=60), nullable=True),
        sa.Column("game_type", sa.String(length=60), nullable=True),
        sa.Column("game_speed", sa.String(length=30), nullable=True),
        sa.Column("starting_age", sa.String(length=30), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("patch", sa.String(length=40), nullable=True),
        sa.Column("patch_low_confidence", sa.Boolean(), nullable=False),
        sa.Column("replay_enhanced", sa.Boolean(), nullable=False),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=60), nullable=False),
        sa.Column("source_range", sa.String(length=40), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_corpus_matches")),
        sa.UniqueConstraint("game_id", name=op.f("uq_corpus_matches_game_id")),
    )
    op.create_index(
        op.f("ix_corpus_matches_leaderboard"), "corpus_matches", ["leaderboard"], unique=False
    )
    op.create_index(
        op.f("ix_corpus_matches_map_name"), "corpus_matches", ["map_name"], unique=False
    )
    op.create_index(op.f("ix_corpus_matches_patch"), "corpus_matches", ["patch"], unique=False)
    op.create_index(
        op.f("ix_corpus_matches_replay_enhanced"),
        "corpus_matches",
        ["replay_enhanced"],
        unique=False,
    )
    op.create_index(
        op.f("ix_corpus_matches_started_at"), "corpus_matches", ["started_at"], unique=False
    )
    op.create_index(
        op.f("ix_corpus_matches_synthetic"), "corpus_matches", ["synthetic"], unique=False
    )
    op.create_table(
        "corpus_rejections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.String(length=64), nullable=False),
        sa.Column("profile_id", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.String(length=60), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("source_range", sa.String(length=40), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_corpus_rejections")),
    )
    op.create_index(
        op.f("ix_corpus_rejections_game_id"), "corpus_rejections", ["game_id"], unique=False
    )
    op.create_index(
        op.f("ix_corpus_rejections_reason"), "corpus_rejections", ["reason"], unique=False
    )
    op.create_index(
        op.f("ix_corpus_rejections_source_range"),
        "corpus_rejections",
        ["source_range"],
        unique=False,
    )
    op.create_table(
        "corpus_players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("match_pk", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.String(length=64), nullable=False),
        sa.Column("profile_id", sa.String(length=64), nullable=False),
        sa.Column("civ", sa.String(length=60), nullable=True),
        sa.Column("winner", sa.Boolean(), nullable=True),
        sa.Column("team", sa.Integer(), nullable=True),
        sa.Column("old_rating", sa.Float(), nullable=True),
        sa.Column("new_rating", sa.Float(), nullable=True),
        sa.Column("elo_band", sa.Integer(), nullable=True),
        sa.Column("feudal_age_uptime", sa.Float(), nullable=True),
        sa.Column("castle_age_uptime", sa.Float(), nullable=True),
        sa.Column("imperial_age_uptime", sa.Float(), nullable=True),
        sa.Column("opening", sa.String(length=60), nullable=True),
        sa.Column("replay_summary_raw", sa.Text(), nullable=True),
        sa.Column("replay_enhanced", sa.Boolean(), nullable=False),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_pk"],
            ["corpus_matches.id"],
            name=op.f("fk_corpus_players_match_pk_corpus_matches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_corpus_players")),
        sa.UniqueConstraint("game_id", "profile_id", name="uq_corpus_player"),
    )
    op.create_index(
        "ix_corpus_players_band_civ", "corpus_players", ["elo_band", "civ"], unique=False
    )
    op.create_index(op.f("ix_corpus_players_civ"), "corpus_players", ["civ"], unique=False)
    op.create_index(
        op.f("ix_corpus_players_elo_band"), "corpus_players", ["elo_band"], unique=False
    )
    op.create_index(op.f("ix_corpus_players_game_id"), "corpus_players", ["game_id"], unique=False)
    op.create_index(
        op.f("ix_corpus_players_old_rating"), "corpus_players", ["old_rating"], unique=False
    )
    op.create_index(op.f("ix_corpus_players_opening"), "corpus_players", ["opening"], unique=False)
    op.create_index(
        op.f("ix_corpus_players_profile_id"), "corpus_players", ["profile_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_corpus_players_profile_id"), table_name="corpus_players")
    op.drop_index(op.f("ix_corpus_players_opening"), table_name="corpus_players")
    op.drop_index(op.f("ix_corpus_players_old_rating"), table_name="corpus_players")
    op.drop_index(op.f("ix_corpus_players_game_id"), table_name="corpus_players")
    op.drop_index(op.f("ix_corpus_players_elo_band"), table_name="corpus_players")
    op.drop_index(op.f("ix_corpus_players_civ"), table_name="corpus_players")
    op.drop_index("ix_corpus_players_band_civ", table_name="corpus_players")
    op.drop_table("corpus_players")
    op.drop_index(op.f("ix_corpus_rejections_source_range"), table_name="corpus_rejections")
    op.drop_index(op.f("ix_corpus_rejections_reason"), table_name="corpus_rejections")
    op.drop_index(op.f("ix_corpus_rejections_game_id"), table_name="corpus_rejections")
    op.drop_table("corpus_rejections")
    op.drop_index(op.f("ix_corpus_matches_synthetic"), table_name="corpus_matches")
    op.drop_index(op.f("ix_corpus_matches_started_at"), table_name="corpus_matches")
    op.drop_index(op.f("ix_corpus_matches_replay_enhanced"), table_name="corpus_matches")
    op.drop_index(op.f("ix_corpus_matches_patch"), table_name="corpus_matches")
    op.drop_index(op.f("ix_corpus_matches_map_name"), table_name="corpus_matches")
    op.drop_index(op.f("ix_corpus_matches_leaderboard"), table_name="corpus_matches")
    op.drop_table("corpus_matches")
    op.drop_index(op.f("ix_cohort_baselines_source"), table_name="cohort_baselines")
    op.drop_index(op.f("ix_cohort_baselines_metric"), table_name="cohort_baselines")
    op.drop_index("ix_baseline_lookup", table_name="cohort_baselines")
    op.drop_table("cohort_baselines")
    # ### end Alembic commands ###
